# This is a basic workflow to help you get started with Actions

name: Deploy CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    container: node:10.18-jessie
    
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - run: npm install
      - name: Generate files
        run: ./node_modules/hexo/bin/hexo g
      
      - name: Optimize font
        run: npm run font

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
# #           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public
#           publish_branch: master  # deploying branch

#       - name: Setup Deploy Private Key
#         env:
#           ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#         run: |
#           mkdir -p ~/.ssh/
#           echo "$ACTIONS_DEPLOY_KEY" > ~/.ssh/id_rsa
#           chmod 700 ~/.ssh
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan github.com >> ~/.ssh/known_hosts
#           git config --global user.email github-actions[bot]@users.noreply.github.com
#           git config --global user.name github-actions[bot]
#           ssh -T git@github.com

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REF: github.com/tkvern/tkvern.github.io
        run: |
          git config --global user.name "tkvern" 
          git config --global user.email "tkvern@qq.com"
          git log --pretty=format:"CI: %s" --date=short -n 1  > commit-message.log
          git clone https://${GH_REF} .deploy_git
          cd .deploy_git
          git checkout master
          cd ../
          mv .deploy_git/.git/ ./public/
          cd ./public/
          git add .
          git commit -F ../commit-message.log
          git push --force --quiet "https://${GITHUB_TOKEN}/@${GH_REF}" master:master
    


